export const teams: string[] = [
  'Actuarial Services',
  'Administration',
  'Business Banking',
  'Centralized Operations',
  'Claims',
  'Client Services',
  'Compliance & Internal Control',
  'Corporate Banking',
  'Customer Experience',
  'Data Analytics and Project Management',
  'Digital Assets',
  'Digital Incubation',
  'Facilities Management',
  'FD/Strategy & FD/PMO',
  'Finance',
  'Financial Control',
  'Financial Institutions',
  'Fixed Income',
  'Front Desk',
  'Global Markets and Treasury',
  'HNI/Partnerships',
  'Human Resources',
  'Information Security',
  'Information Technology',
  'Infrastructure Fund',
  'Innovations',
  'Internal Audit',
  'Internal Control',
  'Investment Banking',
  'Investment Management',
  'Investment Technology',
  'Investor Services',
  'Legal',
  'Marketing & Communications',
  "MD's Office",
  'Operations',
  'Payments & Collections',
  'Private Banking',
  'Products',
  'Public Sector',
  'Registrars Services',
  'Reinsurance',
  'Research',
  'Risk Management',
  'Sales',
  'Sales & Client Coverage',
  'Salvage & Subrogation',
  'Strategy',
  'Survey & Inspection',
  'Talent Management',
  'Technology Shared Services',
  'Trading',
  'Underwriting',
];
