import { CreatePageDto } from '../dto/create-page.dto';
import { DataType } from '../entites.ts/page.entity';

export const pagesData: CreatePageDto[] = [
  {
    url: '/brand-toolkit/brand-basics/introduction#overview',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Brand Basics', 'Introduction'],
    sectionTitle: 'Overview',
    content:
      "Brand guidelines, also known as brand style guides, ensure a consistent and cohesive brand identity. They cover elements like the logo, colour palette, typography, imagery, and brand voice, ensuring all communications reflect the brand's core values and mission accurately. These guidelines are crucial for building brand recognition and trust. They serve as a reference for teams and partners, ensuring consistent visual and verbal identity. This consistency strengthens the brand's reputation and helps it stand out in a competitive marketplace.",
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/our-logo#our-logo',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Our Logo',
    parentPagesTitle: ['Brand Basics', 'Our Logo'],
    sectionTitle: 'Our Logo',
    content:
      'We have two logos. Our primary logo is the Coronation wordmark which is the face of the brand. However, in certain instances, we can use our vertical logos.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/fonts#what-font-to-use',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Fonts',
    parentPagesTitle: ['Brand Basics', 'Fonts'],
    sectionTitle: 'What font to use?',
    content:
      'Lato bold for headlines, subheads, headers, callout and pull quotes. Lato for body copy. Complete sentences should always be in the sentence case.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/fonts#usage',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Fonts',
    parentPagesTitle: ['Brand Basics', 'Fonts'],
    sectionTitle: 'Usage',
    content:
      'Lato is for everyday usage in instances such as email and PowerPoint.Other uses include PowerPoint presentations, charts, graphs, maps, tables, country names, acronyms and abbreviation. Fonts must comply with our fonts guidelines',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/colours#overview',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Colours',
    parentPagesTitle: ['Brand Basics', 'Colours'],
    sectionTitle: 'Overview',
    content:
      'Our colours serve as the foundation of our brand identity, consistently applied to the main text and key elements. They also highlight specific features, add contrast for visual interest, and enhance icons, illustrations, and small elements that need to stand out. The Coronation brand has two distinct colour palettes based on what it is to be used for.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/colours#corporate-palette',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Colours',
    parentPagesTitle: ['Brand Basics', 'Colours'],
    sectionTitle: 'Corporate Palette',
    content:
      'These colours are used in all materials related to or being shared with Corporate (business-to-business) partners. This palette is not to be used for materials related to products marketed to consumers (individuals).',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/colours#consumer-palette',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Colours',
    parentPagesTitle: ['Brand Basics', 'Colours'],
    sectionTitle: 'Consumer Palette',
    content:
      'The colours chosen are subtle yet confident reflecting the Coronation brand sentiment. For consumer-facing applications, brighter shades take priority to achieve a friendlier, more approachable tone. Colours must comply with our colours guidelines',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/photography#overview',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Photography',
    parentPagesTitle: ['Brand Basics', 'Photography'],
    sectionTitle: 'Overview',
    content:
      'Images are an important part of our communication. Our images should consistently follow the rules and guidelines set out. In our visuals, differences are shown in how they are being portrayed to both the Corporate and Consumer Section.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/photography#photography-corporate',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Photography',
    parentPagesTitle: ['Brand Basics', 'Photography'],
    sectionTitle: 'Photography Corporate',
    content:
      'Photography Corporate. These colours are used for materials related to products marketed to businesses. The neutral colours take the lead while the brighter colours should be used as accents where necessary.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/photography#photography-consumer',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Photography',
    parentPagesTitle: ['Brand Basics', 'Photography'],
    sectionTitle: 'Photography Consumer',
    content:
      'Photography Consumer. These colours are used in all materials related to brief shared with consumers.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/faqs/brand-identity',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Brand Identity',
    parentPagesTitle: ['FAQs', 'Brand Identity'],
    content:
      "You will find answers to all your questions about the elements that make up our image, our values, personality, mission, vision, and other visual elements like colour palettes, logos, etc. Brand Identity. How do I create a logo for my team? You can use our designated design tools or consult our brand guidelines for assistance here. What are the main colours from our brand colour palette? Explore the brand colour palette in our brand guidelines to find the main colours. What is our boilerplate? You can find our official boiler plate in the brand portal's resources section or click Brand Guidelines to view the latest version. What is our brand essence? Tap here to explore the core values and unique messaging that make up our brand essence. What is our purpose at Coronation? Coronation's purpose is to create a prosperous future for clients and the African continent. Learn More. What is Coronation's Tone of Voice We sound confident and concise, friendly and approachable, and essentially human.",
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/faqs/vendors-and-third-parties',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Vendors and Third Parties',
    parentPagesTitle: ['FAQs', 'Vendors and Third Parties'],
    content:
      'You will find answers to all your questions about the elements that make up our image, our values, personality, mission, vision, and other visual elements like colour palettes, logos, etc. Vendor and Third Parties. How can my vendor access the brand portal? Your vendor(s) can access the brand portal through a designated login area. You can contact {department} here for the access details. What if an outside party wants to use our logo? For external use of our logo, please follow our logo usage guidelines in the brand portal.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/faqs/templates',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Templates',
    parentPagesTitle: ['FAQs', 'Templates'],
    content:
      'You will find answers to all your questions about the elements that make up our image, our values, personality, mission, vision, and other visual elements like colour palettes, logos, etc. Templates. Where do I find the most recent PowerPoint templates? To find the most recent PowerPoint templates, please visit the PowerPoint templates section available in the brand portal. Where do I find our boiler plate? You can find our boilerplate here in the resources section of the brand portal. Or click on the brand guidelines for more information.',
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/faqs/resources',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Resources',
    parentPagesTitle: ['FAQs', 'Resources'],
    content:
      "You will find answers to all your questions about the elements that make up our image, our values, personality, mission, vision, and other visual elements like colour palettes, logos, etc. Resources. How can I create a new logo? You can create a new logo by checking out our resources on the brand portal or visiting our brand guidelines to get tools and detailed instructions on how to create a new logo. How do I order business cards? You can order for business cards by following the process outlined here in the brand portal or contact department here. How do I create email signatures for my new campaign? In order to create your email signatures, please click on the guidelines provided in the brand portal's resources. Who is a brand ambassador, and how can I become one? To learn about becoming a brand ambassador in our brand ambassador program, click here. How do I access templates for stationery, letterhead, agenda and memos? Find templates for stationery, letterhead, agenda, and memos here. Are there standards for uniforms and equipment? Yes there are requirements and standards for uniforms and equipment. Click here to learn more. Where can I find approved Coronation images? You can access approved coronation images in the resources section of the brand portal. Is there a Coronation template for PowerPoints? Yes, you can find the most recent PowerPoint templates here",
    type: DataType.block,
  },
  {
    url: '/brand-toolkit/brand-basics/introduction',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Brand Toolkit', 'Brand Basics'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/brand-basics/our-logo',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Our Logo',
    parentPagesTitle: ['Brand Toolkit', 'Brand Basics'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/brand-basics/fonts',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Fonts',
    parentPagesTitle: ['Brand Toolkit', 'Brand Basics'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/brand-basics/colours',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Colours',
    parentPagesTitle: ['Brand Toolkit', 'Brand Basics'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/brand-basics/Photography',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Photography',
    parentPagesTitle: ['Brand Toolkit', 'Brand Basics'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/faqs/brand-identity',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Brand Identity',
    parentPagesTitle: ['Brand Toolkit', 'FAQs'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/faqs/vendors-and-third-parties',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Vendors and Third Parties',
    parentPagesTitle: ['Brand Toolkit', 'FAQs'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/faqs/templates',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Templates',
    parentPagesTitle: ['Brand Toolkit', 'FAQs'],
    type: DataType.page,
  },
  {
    url: '/brand-toolkit/faqs/resources',
    documentTitle: 'Brand Toolkit',
    pageTitle: 'Resources',
    parentPagesTitle: ['Brand Toolkit', 'FAQs'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/introduction',
    documentTitle: 'Using our brand',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Using our brand', 'Core Brand Elements'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/logo/wordmark',
    documentTitle: 'Using our brand',
    pageTitle: 'Wordmark',
    parentPagesTitle: ['Core Brand Elements', 'Logo'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/logo/animated-wordmark',
    documentTitle: 'Using our brand',
    pageTitle: 'Animated wordmark',
    parentPagesTitle: ['Core Brand Elements', 'Logo'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/logo/spacing',
    documentTitle: 'Using our brand',
    pageTitle: 'Spacing',
    parentPagesTitle: ['Core Brand Elements', 'Logo'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/colours/introduction',
    documentTitle: 'Using our brand',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Core Brand Elements', 'Colors'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/colours/background-colour',
    documentTitle: 'Using our brand',
    pageTitle: 'Background Colour',
    parentPagesTitle: ['Core Brand Elements', 'Colors'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/typography',
    documentTitle: 'Using our brand',
    pageTitle: 'Typography',
    parentPagesTitle: ['Using our brand', 'Core Brand Elements'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/photography/photography-corporate',
    documentTitle: 'Using our brand',
    pageTitle: 'Photography Corporate',
    parentPagesTitle: ['Core Brand Elements', 'Photography'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/photography/photography-consumer',
    documentTitle: 'Using our brand',
    pageTitle: 'Photography Consumer',
    parentPagesTitle: ['Core Brand Elements', 'Photography'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/icons',
    documentTitle: 'Using our brand',
    pageTitle: 'Icons',
    parentPagesTitle: ['Using our brand', 'Core Brand Elements'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/illustrations',
    documentTitle: 'Using our brand',
    pageTitle: 'Illustrations',
    parentPagesTitle: ['Using our brand', 'Core Brand Elements'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/personality',
    documentTitle: 'Using our brand',
    pageTitle: 'Personality',
    parentPagesTitle: ['Using our brand', 'Core Brand Elements'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/core-brand-elements/faqs',
    documentTitle: 'Using our brand',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Using our brand', 'Core Brand Elements'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/introduction',
    documentTitle: 'Using our brand',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/digital',
    documentTitle: 'Using our brand',
    pageTitle: 'Digital',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/email',
    documentTitle: 'Using our brand',
    pageTitle: 'Email',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/newsletter',
    documentTitle: 'Using our brand',
    pageTitle: 'Newsletter',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/employee-network',
    documentTitle: 'Using our brand',
    pageTitle: 'Employee Network',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/house-style',
    documentTitle: 'Using our brand',
    pageTitle: 'House Style',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/infographics/grouped',
    documentTitle: 'Using our brand',
    pageTitle: 'Grouped',
    parentPagesTitle: ['Brand Application', 'Infographics'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/infographics/ungrouped',
    documentTitle: 'Using our brand',
    pageTitle: 'Ungrouped',
    parentPagesTitle: ['Brand Application', 'Infographics'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/powerpoint-and-presentations/corporate',
    documentTitle: 'Using our brand',
    pageTitle: 'Corporate',
    parentPagesTitle: ['Brand Application', 'Powerpoint Presentations'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/publications/brochure',
    documentTitle: 'Using our brand',
    pageTitle: 'Brochure',
    parentPagesTitle: ['Brand Application', 'Publications'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/publications/flyers',
    documentTitle: 'Using our brand',
    pageTitle: 'Flyers',
    parentPagesTitle: ['Brand Application', 'Publications'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/publications/press-release',
    documentTitle: 'Using our brand',
    pageTitle: 'Press Release',
    parentPagesTitle: ['Brand Application', 'Publications'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/publications/annual-report',
    documentTitle: 'Using our brand',
    pageTitle: 'Annual Report',
    parentPagesTitle: ['Brand Application', 'Publications'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/business-cards',
    documentTitle: 'Using our brand',
    pageTitle: 'Business Cards',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/letterheads',
    documentTitle: 'Using our brand',
    pageTitle: 'Letterheads',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/continuation-sheet',
    documentTitle: 'Using our brand',
    pageTitle: 'Continuation Sheet',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/compliment-slips',
    documentTitle: 'Using our brand',
    pageTitle: 'Compliment Slips',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/envelope',
    documentTitle: 'Using our brand',
    pageTitle: 'Envelope',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/memo',
    documentTitle: 'Using our brand',
    pageTitle: 'Memo',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/forms/form-types',
    documentTitle: 'Using our brand',
    pageTitle: 'Form Types',
    parentPagesTitle: ['Brand Application', 'Forms'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/forms/form-construction',
    documentTitle: 'Using our brand',
    pageTitle: 'Form Construction',
    parentPagesTitle: ['Brand Application', 'Forms'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/forms/form-folder',
    documentTitle: 'Using our brand',
    pageTitle: 'Form Folder',
    parentPagesTitle: ['Brand Application', 'Forms'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/tone-of-voice',
    documentTitle: 'Using our brand',
    pageTitle: 'Tone of Voice',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/sponsorship',
    documentTitle: 'Using our brand',
    pageTitle: 'Sponsorship',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/business-partnerships',
    documentTitle: 'Using our brand',
    pageTitle: 'Business Partnerships',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/merchandise',
    documentTitle: 'Using our brand',
    pageTitle: 'Merchandise',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/faqs',
    documentTitle: 'Using our brand',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/stationery/security-tags-and-lanyards',
    documentTitle: 'Using our brand',
    pageTitle: 'Security Tags & Lanyards',
    parentPagesTitle: ['Brand Application', 'Stationery'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-application/uniform-and-equipment',
    documentTitle: 'Using our brand',
    pageTitle: 'Uniform & Equipment',
    parentPagesTitle: ['Using our brand', 'Brand Application'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/the-coronation-brand/introduction',
    documentTitle: 'Using our brand',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Using our brand', 'The Coronation Brand'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/the-coronation-brand/family-of-verticals',
    documentTitle: 'Using our brand',
    pageTitle: 'Family of Verticals',
    parentPagesTitle: ['Using our brand', 'The Coronation Brand'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/the-coronation-brand/faqs',
    documentTitle: 'Using our brand',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Using our brand', 'The Coronation Brand'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/brand-training',
    documentTitle: 'Using our brand',
    pageTitle: 'Brand Training',
    parentPagesTitle: ['Using our brand'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/introduction',
    documentTitle: 'Using our brand',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/boiler-plates',
    documentTitle: 'Using our brand',
    pageTitle: 'Boiler Plates',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/vertical-narrative',
    documentTitle: 'Using our brand',
    pageTitle: 'Vertical Narrative',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/self-service-elements',
    documentTitle: 'Using our brand',
    pageTitle: 'Self Service Elements',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/other-merchandise',
    documentTitle: 'Using our brand',
    pageTitle: 'Other Merchandise',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/other-stationeries',
    documentTitle: 'Using our brand',
    pageTitle: 'Other Stationeries',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/brand-ambassadors',
    documentTitle: 'Using our brand',
    pageTitle: 'Brand Ambassadors',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/contact-personnel',
    documentTitle: 'Using our brand',
    pageTitle: 'Contact Personnel',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/using-our-brand/narrative/faqs',
    documentTitle: 'Using our brand',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Using our brand', 'Narrative'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-ecosystem/introduction',
    documentTitle: 'Brand in the world',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Brand in the world', 'Coronation Ecosystem'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-ecosystem/verticals',
    documentTitle: 'Brand in the world',
    pageTitle: 'Verticals',
    parentPagesTitle: ['Brand in the world', 'Coronation Ecosystem'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-ecosystem/brand-wheel',
    documentTitle: 'Brand in the world',
    pageTitle: 'Brand Wheel',
    parentPagesTitle: ['Brand in the world', 'Coronation Ecosystem'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-ecosystem/application-portals',
    documentTitle: 'Brand in the world',
    pageTitle: 'Application & Portals',
    parentPagesTitle: ['Brand in the world', 'Coronation Ecosystem'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-ecosystem/faqs',
    documentTitle: 'Brand in the world',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Brand in the world', 'Coronation Ecosystem'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/introduction',
    documentTitle: 'Brand in the world',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/coronation-wealth',
    documentTitle: 'Brand in the world',
    pageTitle: 'Coronation Wealth',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/marine-portal',
    documentTitle: 'Brand in the world',
    pageTitle: 'Marine Portal',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/shareholderlive',
    documentTitle: 'Brand in the world',
    pageTitle: 'ShareholderLive',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/issuerlive',
    documentTitle: 'Brand in the world',
    pageTitle: 'IssuerLive',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/digital-claims',
    documentTitle: 'Brand in the world',
    pageTitle: 'Digital Claims',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/retail-portal',
    documentTitle: 'Brand in the world',
    pageTitle: 'Retail Portal',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/investment-portal',
    documentTitle: 'Brand in the world',
    pageTitle: 'Investment Portal',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/coronation-mobile',
    documentTitle: 'Brand in the world',
    pageTitle: 'Coronation Mobile',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/viva',
    documentTitle: 'Brand in the world',
    pageTitle: 'Viva',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/coronation-platforms/faqs',
    documentTitle: 'Brand in the world',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Brand in the world', 'Coronation Platforms'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/advertising/print-advertising/portrait-layout',
    documentTitle: 'Brand in the world',
    pageTitle: 'Portrait Layout',
    parentPagesTitle: ['Advertising', 'Print Advertising'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/advertising/print-advertising/landscape-layout',
    documentTitle: 'Brand in the world',
    pageTitle: 'Landscape Layout',
    parentPagesTitle: ['Advertising', 'Print Advertising'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/advertising/print-advertising/narrow-layout',
    documentTitle: 'Brand in the world',
    pageTitle: 'Narrow Layout',
    parentPagesTitle: ['Advertising', 'Print Advertising'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/advertising/ooh-advertising/portrait-layout',
    documentTitle: 'Brand in the world',
    pageTitle: 'Portrait Layout',
    parentPagesTitle: ['Advertising', 'OOH Advertising'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/advertising/ooh-advertising/landscape-layout',
    documentTitle: 'Brand in the world',
    pageTitle: 'Landscape Layout',
    parentPagesTitle: ['Advertising', 'OOH Advertising'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/advertising/faqs',
    documentTitle: 'Brand in the world',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Brand in the world', 'Advertising'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/best-of-brands/introduction',
    documentTitle: 'Brand in the world',
    pageTitle: 'Introduction',
    parentPagesTitle: ['Brand in the world', 'Best of Brands'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/best-of-brands/we-are-coronation-owner',
    documentTitle: 'Brand in the world',
    pageTitle: 'We are Coronation - Owner',
    parentPagesTitle: ['Brand in the world', 'Best of Brands'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/best-of-brands/transformed-africa',
    documentTitle: 'Brand in the world',
    pageTitle: 'Transformed Africa',
    parentPagesTitle: ['Brand in the world', 'Best of Brands'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/best-of-brands/bancassurance',
    documentTitle: 'Brand in the world',
    pageTitle: 'Bancassurance',
    parentPagesTitle: ['Brand in the world', 'Best of Brands'],
    type: DataType.page,
  },
  {
    url: '/brand-in-the-world/best-of-brands/faqs',
    documentTitle: 'Brand in the world',
    pageTitle: 'FAQs',
    parentPagesTitle: ['Brand in the world', 'Best of Brands'],
    type: DataType.page,
  },
];
